<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
        <artifactId>pluginsib-documentcustody</artifactId>
        <version>5.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>pluginsib-documentcustody-alfresco</artifactId>
    <packaging>jar</packaging>
    <name>PluginsIB - Document Custody - Alfresco</name>

    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
            <artifactId>pluginsib-documentcustody-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.chemistry.opencmis</groupId>
            <artifactId>chemistry-opencmis-client-impl</artifactId>
            <version>0.9.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.xml.ws</groupId>
                    <artifactId>jaxws-rt</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.apache.chemistry.opencmis</groupId>
            <artifactId>chemistry-opencmis-client-bindings</artifactId>
            <version>0.9.0</version>
        </dependency>
        <dependency>
            <groupId>org.alfresco.cmis.client</groupId>
            <artifactId>alfresco-opencmis-extension</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.http-client</groupId>
            <artifactId>google-http-client-jackson</artifactId>
            <version>1.16.0-rc</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.documentcustody</groupId>
            <artifactId>pluginsib-documentcustody-api</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
            <classifier>tests</classifier>
        </dependency>
    </dependencies>
    
        <profiles>
        <!-- Profile jboss72: actiu per defecte -->
        <profile>
            <id>jboss72_def</id>
            <activation>
                <property>
                    <name>!jboss</name>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                    <version>1.3.9</version>
                </dependency>
            </dependencies>
        </profile>
        <!-- Profile jboss72: actiu per propietat -->
        <profile>
            <id>jboss72_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.2</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.2 -->
                <dependency>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                    <version>1.3.9</version>
                </dependency>
            </dependencies>
        </profile>
        <!-- Profile jboss74: actiu per propietat -->
        <profile>
            <id>jboss74_explicit</id>
            <activation>
                <property>
                    <name>jboss</name>
                    <value>7.4</value>
                </property>
            </activation>
            <dependencies>
                <!-- Dependències específiques per a JBoss 7.4 -->
                <dependency>
                    <groupId>com.google.code.findbugs</groupId>
                    <artifactId>jsr305</artifactId>
                    <version>3.0.2</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>

</project>
